//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int courseNumber { get; set; }
        public string courseName { get; set; }
        public string Description { get; set; }
        public int levelNumber { get; set; }
        public int labNumber { get; set; }
        public int floorNumber { get; set; }
        public int tNumber { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual Lab Lab { get; set; }
        public virtual Level Level { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
