//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall
    {
        public int hallNumber { get; set; }
        public int floorNumber { get; set; }
    
        public virtual Floor Floor { get; set; }
    }
}
